version: 2

models:
    - name: dbt_product
      description: "A starter dbt model"
      columns:
          - name: productid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: dim_sales
      description: "A starter dbt model"
      columns:
          - name: salespersonid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null