
version: 2

models:
    - name: dim_product
      description: "A starter dbt model"
      columns:
          - name: productid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: dim_sales
      description: "A starter dbt model"
      columns:
          - name: sales_personid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: sales
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
                 

                               


