version: 2
sources:
 - name: dbt_demo
    schema: dbt_atefera
    tables:
        - name: sales_source
          identifier: sales_source
        - name: dim_product
          identifier: dim_product
        - name: dim_sales
          identifier: dim_sales
    loaded_at_field: date
    freshness:
        warn_after: {count: 1, period: hour}
        error_after: {count: 24, period: hour}