
version: 2
sources:
  - name: dbt_demo
    schema: demo
    tables:
        - name: dim_product
          identifier:  product_listing
 
        - name: dim_sales_product
          identifier: sales_product_listing

        - name: sales
          identifier: sales_listing
